/** Chaves de cache centralizadas: invalidacao previsivel e sem string solta. */
export const queryKeys = {
  session: ['session'] as const,
  home: ['home'] as const,
  feed: (scope: string) => ['feed', scope] as const,
  books: (filters: object) => ['books', filters] as const,
  book: (slug: string) => ['book', slug] as const,
  bookSearch: (q: string) => ['book-search', q] as const,
  genres: ['genres'] as const,
  library: (status?: string) => ['library', status ?? 'all'] as const,
  communities: (filters: object) => ['communities', filters] as const,
  community: (slug: string) => ['community', slug] as const,
  communityPosts: (slug: string, sort: string) => ['community-posts', slug, sort] as const,
  communityMembers: (slug: string, status: string) => ['community-members', slug, status] as const,
  communityAnalytics: (slug: string) => ['community-analytics', slug] as const,
  recommendedCommunities: ['recommended-communities'] as const,
  post: (id: string) => ['post', id] as const,
  profile: (username: string) => ['profile', username] as const,
  profilePosts: (username: string) => ['profile-posts', username] as const,
  connections: (username: string, kind: string) => ['connections', username, kind] as const,
  suggestedPeople: (bookId?: string) => ['suggested-people', bookId ?? 'all'] as const,
  notifications: ['notifications'] as const,
  unreadCount: ['notifications', 'unread'] as const,
  conversations: ['conversations'] as const,
  conversation: (id: string) => ['conversation', id] as const,
  search: (q: string) => ['search', q] as const,
  trending: ['trending'] as const,
  exploreDiscussions: (genre?: string) => ['explore-discussions', genre ?? 'all'] as const,
  stats: ['stats'] as const,
  achievements: ['achievements'] as const,
  plans: ['plans'] as const,
  planUsage: ['plan-usage'] as const,
  savedPosts: ['saved-posts'] as const,
};
